services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/VladimirKomov/sharing-things-app.git
    branch: dev
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: CHOKIDAR_USEPOLLING
        value: true
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    repo: https://github.com/VladimirKomov/sharing-things-app.git
    branch: dev
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DB_NAME
        value: sharing_db
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: 5432
    autoDeploy: true



