services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/VladimirKomov/sharing-things-app.git
    branch: dev
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: CHOKIDAR_USEPOLLING
        value: true
    autoDeploy: true

  - type: web
    name: backend
    env: docker
    repo: https://github.com/VladimirKomov/sharing-things-app.git
    branch: dev
    dockerfilePath: ./backend/Dockerfile
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
    envFilePath: ./backend/.env
    autoDeploy: true
    dependencies:
      - name: db

  - type: database
    name: db
    plan: starter
    properties:
      databaseName: sharing_db
      user: postgres
      password: 321test123
      port: 5432
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: 321test123
      - key: POSTGRES_DB
        value: sharing_db

volumes:
  - name: db_data
    mountPath: /var/lib/postgresql/data
