# Generated by Django 5.1.2 on 2024-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('returned', 'Returned'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
