# Generated by Django 5.1.2 on 2024-11-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
