# Generated by Django 5.1.2 on 2024-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_usersettings_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
