# Generated by Django 5.1.2 on 2024-11-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_result'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemrating',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemrating',
            unique_together={('order', 'user')},
        ),
    ]
