# Generated by Django 5.1.2 on 2024-11-12 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_result'),
        ('ratings', '0002_alter_itemrating_unique_together_itemrating_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userrating',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_rating', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('order', 'reviewer')},
        ),
    ]
